POS/POS.web/Controllers/OrderDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using POS.Repository;
using POS.Service;
using POS.ViewModel;

namespace POS.web.Controllers
{
    public class OrderDetailsController : Controller
    {
        private readonly OrderDetailService _service;

        public OrderDetailsController(ApplicationContext context)
        {
            _service = new OrderDetailService(context);
        }

        [HttpGet]
        public IActionResult List()
        {
            var Data = _service.GetEntities();
            return View(Data);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            var Data = _service.Find(id);
            return View(Data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddModal()
        {
            return PartialView("_Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("OrderId, ProductId, UnitPrice, Quantity, Discount")] OrderDetailsModel request)
        {
            if (ModelState.IsValid)
            {
                _service.Add(new OrderDetailsEntity(request));
                return Redirect("List");
            }
            return View("Add", request);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var Data = _service.Find(id);
            return View(Data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update([Bind("OrderId, ProductId, UnitPrice, Quantity, Discount")] OrderDetailsModel request)
        {
            if (ModelState.IsValid)
            {
                _service.Update(request);
                return Redirect("List");
            }
            return View("Edit", request);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            _service.Delete(id);
            return Redirect("/OrderDetails/List");
        }
    }
}

POS/POS.web/Views/OrderDetails/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@model POS.Repository.OrderDetailsEntity*@
@model POS.ViewModel.OrderDetailsModel
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Order Details</h2>
<form asp-action="Save" asp-controller="OrderDetails" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="OrderId"></label>
        <input asp-for="OrderId" class="form-control" />
        <span asp-validation-for="OrderId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ProductId"></label>
        <input asp-for="ProductId" class="form-control" />
        <span asp-validation-for="ProductId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="UnitPrice"></label>
        <input asp-for="UnitPrice" class="form-control" />
        <span asp-validation-for="UnitPrice" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Quantity"></label>
        <input asp-for="Quantity" class="form-control" />
        <span asp-validation-for="Quantity" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Discount"></label>
        <input asp-for="Discount" class="form-control" />
        <span asp-validation-for="Discount" class="text-danger" />
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.web/Views/OrderDetails/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model POS.Repository.OrderDetailsEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Delete</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to delete this?</h3>
<form asp-action="List" method="get">
    <button type="submit" class="btn btn-primary">Yes</button>
</form>

POS/POS.web/Views/OrderDetails/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@model POS.Repository.OrderDetailsEntity*@
@model POS.ViewModel.OrderDetailsModel
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Order Details</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.OrderId</td>
    </tr>
    <tr>
        <th>Category Name</th>
        <td>@Model.ProductId</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.UnitPrice</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.Quantity</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.Discount</td>
    </tr>

</table>

POS/POS.web/Views/OrderDetails/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@model POS.Repository.OrderDetailsEntity*@
@model POS.ViewModel.OrderDetailsModel
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Edit Order Details</h2>
<form asp-action="Update" asp-controller="OrderDetails" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="OrderId"></label>
        <input asp-for="OrderId" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="ProductId"></label>
        <input asp-for="ProductId" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="UnitPrice"></label>
        <input asp-for="UnitPrice" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Quantity"></label>
        <input asp-for="Quantity" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Discount"></label>
        <input asp-for="Discount" class="form-control" />
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.web/Views/OrderDetails/List.cshtml
@model IEnumerable<POS.Repository.OrderDetailsEntity>
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Order Details</h2>
<table class="table table-bordered table-dark ">
    <thead class="align-middle text-center">
        <tr>
            <th>ID</th>
            <th>Order ID</th>
            <th>Product Id</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Discount</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>@item.Id</td>
                <td>@item.OrderId</td>
                <td>@item.ProductId</td>
                <td>@item.UnitPrice</td>
                <td>@item.Quantity</td>
                <td>@item.Discount</td>
                <td class="align-middle text-center">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                        Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                            <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                        </svg>
                        View</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                        </svg>
                        Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Add" class="btn btn-primary" role="button" id="btn-add">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z" />
    </svg>
    Add
</a>
<div class="modal" tabindex="-1" id="my-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Order Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            
        </div>
    </div>
</div>
@section Scripts
    {
    <script type="text/javascript">    
        $("#btn-add").on("click", function (e) {
            e.preventDefault();
            $.ajax({
                url:"AddModal",
                type:"GET",
                dataType:"html",
                success:function(data){
                    $("#my-modal").find(".modal-body").html(data);
                    $("#my-modal").modal("show");
                }
            });
            
        });
    </script>
}

POS/POS.web/Views/OrderDetails/_Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@model POS.Repository.OrderDetailsEntity*@
@model POS.ViewModel.OrderDetailsModel

<form asp-action="Save" asp-controller="OrderDetails" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="OrderId"></label>
        <input asp-for="OrderId" class="form-control" />
        <span asp-validation-for="OrderId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ProductId"></label>
        <input asp-for="ProductId" class="form-control" />
        <span asp-validation-for="ProductId" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="UnitPrice"></label>
        <input asp-for="UnitPrice" class="form-control" />
        <span asp-validation-for="UnitPrice" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Quantity"></label>
        <input asp-for="Quantity" class="form-control" />
        <span asp-validation-for="Quantity" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Discount"></label>
        <input asp-for="Discount" class="form-control" />
        <span asp-validation-for="Discount" class="text-danger" />
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}