POS/POS.web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using POS.Repository;
using POS.Service;
using POS.ViewModel;

namespace POS.web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly CustomerService _service;

        public CustomerController(ApplicationContext context)
        {
            _service = new CustomerService(context);
        }
        
        [HttpGet]
        public IActionResult List()
        {
            var Data = _service.GetEntities();
            return View(Data);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            var Data = _service.Find(id);
            return View(Data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddModal()
        {
            return PartialView("_Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("CompanyName, ContactName, ContactTitle, Address, City, Region, PostalCode, Country, Phone, Fax")] CustomerModel request)
        {
            if (ModelState.IsValid)
            {
                _service.Add(new CustomersEntity(request));
                return Redirect("List");
            }
            return View("Add", request);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var Data = _service.Find(id);
            return View(Data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update([Bind("CustomerId, CompanyName, ContactName, ContactTitle, Address, City, Region, PostalCode, Country, Phone, Fax")] CustomerModel request)
        {
            if (ModelState.IsValid)
            {
                _service.Update(request);
                return Redirect("List");
            }
            return View("Edit", request);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            _service.Delete(id);
            return Redirect("/Customer/List");
        }
    }
}

POS/POS.web/Controllers/SuppliersController.cs
using Microsoft.AspNetCore.Mvc;
using POS.Repository;
using POS.Service;
using POS.ViewModel;

namespace POS.web.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly SupplierService _service;

        public SuppliersController(ApplicationContext context)
        {
            _service = new SupplierService(context);
        }

        [HttpGet]
        public IActionResult List()
        {
            var Data = _service.GetEntities();
            return View(Data);
        }


        [HttpGet]
        public IActionResult Details(int? id)
        {
            var Data = _service.Find(id);
            return View(Data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddModal()
        {
            return PartialView("_Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("CompanyName, ContactName, ContactTitle, Address, City, Region, PostalCode, Country, Phone, Fax, HomePage")] SupplierModel request)
        {
            if (ModelState.IsValid)
            {
                _service.Add(new SuppliersEntity(request));
                return Redirect("List");
            }
            return View("Add", request);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var Data = _service.Find(id);
            return View(Data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update([Bind("SupplierId, CompanyName, ContactName, ContactTitle, Address, City, Region, PostalCode, Country, Phone, Fax, HomePage")] SupplierModel request)
        {
            if (ModelState.IsValid)
            {
                //SuppliersEntity suppliersEntity = new SuppliersEntity(supplier);
                //suppliersEntity.SupplierId = supplier.SupplierId;
                _service.Update(request);
                return Redirect("List");
            }
            return View("Edit", request);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            //var entity = _service.Find(id);
            _service.Delete(id);
            return Redirect("/Suppliers/List");
        }
    }
}

POS/POS.web/Views/Customer/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@model POS.Repository.CustomersEntity*@
@model POS.ViewModel.CustomerModel
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Add Customer</h2>
<form asp-action="Save" asp-controller="Suppliers" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ContactName"></label>
        <input asp-for="ContactName" class="form-control" />
        <span asp-validation-for="ContactName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ContactTitle"></label>
        <input asp-for="ContactTitle" class="form-control" />
        <span asp-validation-for="ContactTitle" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Region"></label>
        <input asp-for="Region" class="form-control" />
        <span asp-validation-for="Region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Fax"></label>
        <input asp-for="Fax" class="form-control" />
        <span asp-validation-for="Fax" class="text-danger" />
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.web/Views/Customer/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model POS.Repository.CustomersEntity
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<h2>Delete</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to delete this?</h3>
<form asp-action="List" method="get">
    <button type="submit" class="btn btn-primary">Yes</button>
</form>

POS/POS.web/Views/Customer/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@model POS.Repository.CustomersEntity*@
@model POS.ViewModel.CustomerModel
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<div class="col-xl-12 col-md-12">
    <div class="card">
        <div class="card-header">
            <h3>Customer Detail</h3>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <tr>
                    <th>Id</th>
                    <td>@Model.CustomerId</td>
                </tr>
                <tr>
                    <th>Company Name</th>
                    <td>@Model.CompanyName</td>
                </tr>
                <tr>
                    <th>Contact Name</th>
                    <td>@Model.ContactName</td>
                </tr>
                <tr>
                    <th>Contact Title</th>
                    <td>@Model.ContactTitle</td>
                </tr>
                <tr>
                    <th>Address</th>
                    <td>@Model.Address</td>
                </tr>
                <tr>
                    <th>City</th>
                    <td>@Model.City</td>
                </tr>
                <tr>
                    <th>Region</th>
                    <td>@Model.Region</td>
                </tr>
                <tr>
                    <th>Postal Code</th>
                    <td>@Model.PostalCode</td>
                </tr>
                <tr>
                    <th>Country</th>
                    <td>@Model.Country</td>
                </tr>
                <tr>
                    <th>Phone</th>
                    <td>@Model.Phone</td>
                </tr>
                <tr>
                    <th>Fax</th>
                    <td>@Model.Fax</td>
                </tr>

            </table>
        </div>

    </div>

</div>

POS/POS.web/Views/Customer/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model POS.ViewModel.CustomerModel
@{
    ViewBag.Title = "Title";
    Layout = "_Layout";
}

<div class="col-xl-12 col-md-12">
    <div class="card">
        <div class="card-header">
            <h3>Edit Customer</h3>
        </div>
        <div class="card-body">
            <form asp-action="Update" asp-controller="Customer" method="post">
                <input type="hidden" asp-for="CustomerId" />
                <div class="form-group">
                    <label asp-for="CompanyName">Company Name</label>
                    <input asp-for="CompanyName" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="ContactName">Contact Name</label>
                    <input asp-for="ContactName" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="ContactTitle">Contact Title</label>
                    <input asp-for="ContactTitle" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Address">Address</label>
                    <input asp-for="Address" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="City">City</label>
                    <input asp-for="City" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Region">Region</label>
                    <input asp-for="Region" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="PostalCode">Postal Code</label>
                    <input asp-for="PostalCode" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Country">Country</label>
                    <input asp-for="Country" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Phone">Phone</label>
                    <input asp-for="Phone" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Fax">Fax</label>
                    <input asp-for="Fax" class="form-control" />
                </div>

                <div class="form-footer">
                    <button type="submit" class="btn btn-warning">Update</button>
                </div>

            </form>
        </div>

    </div>

</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

POS/POS.web/Views/Customer/List.cshtml
@model IEnumerable<POS.Repository.CustomersEntity>
@{
    ViewBag.Title = "Customer";
    Layout = "_Layout";

}

@*<h2>All Customer</h2>*@
<div class="col-xl-12 col-md-6">
    <div class="card">
        <div class="card-header">
            <h3>Customer</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <thead class="align-middle text-center">
                        <tr>
                            <th>ID</th>
                            <th>Company Name</th>
                            <th>Contact Name</th>
                            <th>Contact Title</th>
                            <th>Address</th>
                            <th>City</th>
                            <th>Region</th>
                            <th>Postal Code</th>
                            <th>Country</th>
                            <th>Phone</th>
                            <th>Fax</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="text-center">
                                <td>@item.CustomerId</td>
                                <td>@item.CompanyName</td>
                                <td>@item.ContactName</td>
                                <td>@item.ContactTitle</td>
                                <td>@item.Address</td>
                                <td>@item.City</td>
                                <td>@item.Region</td>
                                <td>@item.PostalCode</td>
                                <td>@item.Country</td>
                                <td>@item.Phone</td>
                                <td>@item.Fax</td>
                                <td class="align-middle text-center">
                                    <a asp-action="Edit" asp-route-id="@item.CustomerId" class="badge badge-warning">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                        </svg>
                                    </a>
                                    <a asp-action="Details" asp-route-id="@item.CustomerId" class="badge badge-success">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                                            <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                                        </svg>
                                    </a>
                                    <a asp-action="Delete" asp-route-id="@item.CustomerId" class="badge badge-danger">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>

    </div>
</div>

<a asp-action="Add" class="btn btn-primary" role="button" id="btn-add">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z" />
    </svg>
    Add
</a>
<div class="modal" tabindex="-1" id="my-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Customer</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>

        </div>
    </div>
</div>
@section Scripts
    {
    <script type="text/javascript">
        $("#btn-add").on("click", function (e) {
            e.preventDefault();
            $.ajax({
                url:"AddModal",
                type:"GET",
                dataType:"html",
                success: function (data) {
                    $("#my-modal").find(".modal-body").html(data);
                    $("#my-modal").modal("show");
                }
            });

        });
    </script>
}

POS/POS.web/Views/Customer/_Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@model POS.Repository.CustomersEntity*@
@model POS.ViewModel.CustomerModel

<form asp-action="Save" asp-controller="Customer" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="CompanyName">Company Name</label>
        <input asp-for="CompanyName" class="form-control" />
        <span asp-validation-for="CompanyName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ContactName">Contact Name</label>
        <input asp-for="ContactName" class="form-control" />
        <span asp-validation-for="ContactName" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="ContactTitle">Contact Title</label>
        <input asp-for="ContactTitle" class="form-control" />
        <span asp-validation-for="ContactTitle" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Address">Address</label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="City">City</label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Region">Region</label>
        <input asp-for="Region" class="form-control" />
        <span asp-validation-for="Region" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode">Postal Code</label>
        <input asp-for="PostalCode" class="form-control" />
        <span asp-validation-for="PostalCode" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Country">Country</label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Phone">Phone</label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger" />
    </div>
    <div class="form-group">
        <label asp-for="Fax">Fax</label>
        <input asp-for="Fax" class="form-control" />
        <span asp-validation-for="Fax" class="text-danger" />
    </div>

    @*<div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>*@
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}